CREATE TABLE `local_route_hotspot` (
	`route_id` text NOT NULL,
	`month` text NOT NULL,
	`hotspot_rank` integer NOT NULL,
	`segment_id` text NOT NULL,
	`direction` text NOT NULL,
	`stop_order` integer NOT NULL,
	`timepoint_stop_id` text NOT NULL,
	`timepoint_stop_name` text NOT NULL,
	`next_timepoint_stop_id` text NOT NULL,
	`next_timepoint_stop_name` text NOT NULL,
	`observation_count` integer NOT NULL,
	`bus_trip_count` integer NOT NULL,
	`weighted_average_speed_mph` real NOT NULL,
	`weighted_average_travel_time_minutes` real NOT NULL,
	`average_road_distance_miles` real NOT NULL,
	`slow_window_share` real NOT NULL,
	`speed_severity` real NOT NULL,
	`hotspot_score` integer NOT NULL,
	`ridership_exposure` real,
	`transfer_exposure` real,
	`rider_delay_index` real,
	`rider_impact_share` real,
	`rider_weighted_speed_severity` real,
	`rider_weighted_slow_window_share` real,
	`rider_impact_score` integer,
	PRIMARY KEY(`route_id`, `month`, `hotspot_rank`)
);
--> statement-breakpoint
CREATE TABLE `local_route_hotspot_summary` (
	`route_id` text NOT NULL,
	`month` text NOT NULL,
	`generated_at` text NOT NULL,
	`route_weighted_average_speed_mph` real NOT NULL,
	`observation_count` integer NOT NULL,
	`bus_trip_count` integer NOT NULL,
	`ridership_weighted` integer NOT NULL,
	`ridership_window_count` integer NOT NULL,
	`ridership_matched_observation_count` integer NOT NULL,
	`ridership_exposure` real NOT NULL,
	`segment_count` integer NOT NULL,
	`hotspot_count` integer NOT NULL,
	PRIMARY KEY(`route_id`, `month`)
);
