/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as DigestRouteImport } from "./routes/digest"
import { Route as CompareRouteImport } from "./routes/compare"
import { Route as SplatRouteImport } from "./routes/$"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as RoutesRouteIdRouteImport } from "./routes/routes/$routeId"

const DigestRoute = DigestRouteImport.update({
  id: "/digest",
  path: "/digest",
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: "/compare",
  path: "/compare",
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdRoute = RoutesRouteIdRouteImport.update({
  id: "/routes/$routeId",
  path: "/routes/$routeId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/$": typeof SplatRoute
  "/compare": typeof CompareRoute
  "/digest": typeof DigestRoute
  "/routes/$routeId": typeof RoutesRouteIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/$": typeof SplatRoute
  "/compare": typeof CompareRoute
  "/digest": typeof DigestRoute
  "/routes/$routeId": typeof RoutesRouteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/$": typeof SplatRoute
  "/compare": typeof CompareRoute
  "/digest": typeof DigestRoute
  "/routes/$routeId": typeof RoutesRouteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/$" | "/compare" | "/digest" | "/routes/$routeId"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/$" | "/compare" | "/digest" | "/routes/$routeId"
  id: "__root__" | "/" | "/$" | "/compare" | "/digest" | "/routes/$routeId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CompareRoute: typeof CompareRoute
  DigestRoute: typeof DigestRoute
  RoutesRouteIdRoute: typeof RoutesRouteIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/digest": {
      id: "/digest"
      path: "/digest"
      fullPath: "/digest"
      preLoaderRoute: typeof DigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/compare": {
      id: "/compare"
      path: "/compare"
      fullPath: "/compare"
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$": {
      id: "/$"
      path: "/$"
      fullPath: "/$"
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/routes/$routeId": {
      id: "/routes/$routeId"
      path: "/routes/$routeId"
      fullPath: "/routes/$routeId"
      preLoaderRoute: typeof RoutesRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CompareRoute: CompareRoute,
  DigestRoute: DigestRoute,
  RoutesRouteIdRoute: RoutesRouteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
