/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as MethodsRouteImport } from "./routes/methods"
import { Route as MapRouteImport } from "./routes/map"
import { Route as InterventionsRouteImport } from "./routes/interventions"
import { Route as SplatRouteImport } from "./routes/$"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as RoutesIndexRouteImport } from "./routes/routes/index"
import { Route as RoutesRouteIdRouteImport } from "./routes/routes/$routeId"

const MethodsRoute = MethodsRouteImport.update({
  id: "/methods",
  path: "/methods",
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: "/map",
  path: "/map",
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionsRoute = InterventionsRouteImport.update({
  id: "/interventions",
  path: "/interventions",
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: "/routes/",
  path: "/routes/",
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdRoute = RoutesRouteIdRouteImport.update({
  id: "/routes/$routeId",
  path: "/routes/$routeId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/$": typeof SplatRoute
  "/interventions": typeof InterventionsRoute
  "/map": typeof MapRoute
  "/methods": typeof MethodsRoute
  "/routes": typeof RoutesIndexRoute
  "/routes/$routeId": typeof RoutesRouteIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/$": typeof SplatRoute
  "/interventions": typeof InterventionsRoute
  "/map": typeof MapRoute
  "/methods": typeof MethodsRoute
  "/routes": typeof RoutesIndexRoute
  "/routes/$routeId": typeof RoutesRouteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/$": typeof SplatRoute
  "/interventions": typeof InterventionsRoute
  "/map": typeof MapRoute
  "/methods": typeof MethodsRoute
  "/routes/": typeof RoutesIndexRoute
  "/routes/$routeId": typeof RoutesRouteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/$"
    | "/interventions"
    | "/map"
    | "/methods"
    | "/routes"
    | "/routes/$routeId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/$"
    | "/interventions"
    | "/map"
    | "/methods"
    | "/routes"
    | "/routes/$routeId"
  id:
    | "__root__"
    | "/"
    | "/$"
    | "/interventions"
    | "/map"
    | "/methods"
    | "/routes/"
    | "/routes/$routeId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  InterventionsRoute: typeof InterventionsRoute
  MapRoute: typeof MapRoute
  MethodsRoute: typeof MethodsRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
  RoutesRouteIdRoute: typeof RoutesRouteIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/methods": {
      id: "/methods"
      path: "/methods"
      fullPath: "/methods"
      preLoaderRoute: typeof MethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/map": {
      id: "/map"
      path: "/map"
      fullPath: "/map"
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/interventions": {
      id: "/interventions"
      path: "/interventions"
      fullPath: "/interventions"
      preLoaderRoute: typeof InterventionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$": {
      id: "/$"
      path: "/$"
      fullPath: "/$"
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/routes/$routeId": {
      id: "/routes/$routeId"
      path: "/routes/$routeId"
      fullPath: "/routes/$routeId"
      preLoaderRoute: typeof RoutesRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/routes/": {
      id: "/routes/"
      path: "/routes"
      fullPath: "/routes"
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  InterventionsRoute: InterventionsRoute,
  MapRoute: MapRoute,
  MethodsRoute: MethodsRoute,
  RoutesIndexRoute: RoutesIndexRoute,
  RoutesRouteIdRoute: RoutesRouteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
