CREATE TABLE `local_weather_observation` (
	`station_id` text NOT NULL,
	`date` text NOT NULL,
	`station_name` text,
	`latitude` real,
	`longitude` real,
	`elevation_m` real,
	`prcp_mm` real,
	`snow_mm` real,
	`snwd_mm` real,
	`tmax_c` real,
	`tmin_c` real,
	`tavg_c` real,
	`awnd_ms` real,
	`has_fog` integer,
	`has_thunder` integer,
	`has_sleet` integer,
	`has_hail` integer,
	`has_high_wind` integer,
	`has_rain` integer,
	`has_snow` integer,
	`ingested_at` text NOT NULL,
	PRIMARY KEY(`station_id`, `date`)
);
