// AUTO-GENERATED by `studio release` (tools/pipeline-v2/src/commands/studio/_release-seo.ts).
// Do not edit by hand. Regenerate with: bun --filter @bp/web build:studio-release
export const SEO_MANIFEST_GENERATED_AT = "2026-05-25T20:11:06.387Z";

export const routeTitles: ReadonlyMap<string, string> = new Map([
  ["m15-sbs", "M15 SBS"],
  ["bx12-sbs", "Bx12 SBS"],
  ["b25", "B25"],
  ["bx41", "Bx41"],
  ["m101", "M101"],
  ["b41", "B41"],
  ["b46-sbs", "B46 SBS"],
  ["q58", "Q58"],
  ["m14a-sbs", "M14A SBS"],
  ["m14d-sbs", "M14D SBS"],
  ["m57", "M57"],
  ["m42", "M42"],
]);
