// AUTO-GENERATED by `studio release` (tools/pipeline-v2/src/commands/studio/_release-seo.ts).
// Do not edit by hand. Regenerate with: bun --filter @bp/web build:studio-release
export const SEO_MANIFEST_GENERATED_AT = "2026-05-25T20:11:06.387Z";

export const routeTitles: ReadonlyMap<string, string> = new Map([
  ["m15-sbs", "M15 SBS"],
  ["bx12-sbs", "Bx12 SBS"],
  ["b25", "B25"],
  ["bx41", "Bx41"],
  ["m101", "M101"],
  ["b41", "B41"],
  ["b46-sbs", "B46 SBS"],
  ["q58", "Q58"],
  ["m14a-sbs", "M14A SBS"],
  ["m14d-sbs", "M14D SBS"],
  ["m57", "M57"],
  ["m42", "M42"],
]);

export const findingTitles: ReadonlyMap<string, string> = new Map([
  ["b25-fulton-corridor-reliability-permits", "B25 reliability problems persisted as March street-work context clustered nearby"],
  ["bx41-webster-reliability-permits", "BX41 pairs persistent reliability trouble with Webster Avenue street-work context"],
  ["promoted-promoted_finding_fe444ebdbb538ef404ba9f69faf2077d", "M57: Multi Month Peer Speed Deficit"],
  ["promoted-promoted_finding_16e8194527e64bf71a38c7638a078983", "M42: Persistent Low Speed"],
  ["promoted-promoted_finding_fbf9eb6057ab6a177c77063e2dc08d99", "M57: Persistent Low Speed"],
  ["promoted-promoted_finding_40ecf94f0df83c550a7340d57a26edc6", "M101: Persistent Low Speed"],
  ["promoted-promoted_finding_072be6950457379ff1b4652d988be5dd", "M42: Permit Correlated Slowdown"],
  ["promoted-promoted_finding_17297306bba862e94436e165f4e5dd3f", "M101: Permit Correlated Slowdown"],
  ["promoted-promoted_finding_d1844cd48f54916449850cce2470c3ac", "B41: High Long Gap Share"],
  ["promoted-promoted_finding_fb710c30c0b4e65d455e7eac44f93d88", "Q58: High Long Gap Share"],
]);

export const briefTitles: ReadonlyMap<string, string> = new Map([
  ["m15-madison-corridor", "The Madison corridor problem"],
  ["bx12-treatment-benchmark", "Bx12 SBS treatment benchmark"],
  ["brief-b25", "B25 Dwntn Bklyn & DUMBO - Broadway Junction reliability brief"],
  ["brief-bx41", "Bx41 Williamsbridge - The Hub reliability brief"],
  ["brief-m101", "M101 East Village - Fort George reliability brief"],
  ["brief-b41", "B41 Kings Plaza - Downtown Brooklyn reliability brief"],
  ["brief-b46-sbs", "B46 Kings Plaza - Williamsburg reliability brief"],
  ["brief-q58", "Q58 Ridgewood - Flushing reliability brief"],
  ["brief-m14a-sbs", "M14A Lower East Side - Abingdon Sq reliability brief"],
  ["brief-m14d-sbs", "M14D Lower East Side - Chelsea Piers reliability brief"],
  ["brief-m57", "M57 East Side - West Side reliability brief"],
  ["brief-m42", "M42 United Nations - W 42 St Pier reliability brief"],
]);
