import type { StudioApiEnv } from "@bp/studio-api/server";

export type Env = StudioApiEnv & {
  ASSETS?: Fetcher;
  CF_VERSION_METADATA?: WorkerVersionMetadata;
  PLAN097_OPERATIONS?: R2Bucket;
  PLAN097_PROOF_BUNDLES?: R2Bucket;
  PLAN097_PROOF_ARTIFACTS?: R2Bucket;
  PLAN097_PROOF_RECEIPTS?: R2Bucket;
  PLAN097_RECOVERY_OPERATION_ENABLED?: string;
  PLAN097_OPERATION_ID?: string;
  PLAN097_ACTIVATION_BUNDLE_SHA256?: string;
  PLAN097_RESTORE_BUNDLE_SHA256?: string;
  PLAN097_PREFLIGHT_RECEIPT_SHA256?: string;
  PLAN097_ACCESS_TEAM_DOMAIN?: string;
  PLAN097_ACCESS_AUD?: string;
  PLAN097_ACCESS_SERVICE_TOKEN_ID?: string;
  PLAN097_EXECUTION_TOKEN?: string;
  PLAN097_PROOF_MODE?: string;
  PLAN097_SEED_MODE?: string;
  PLAN097_REPO_SHA?: string;
  PLAN097_COMMAND_VERSION?: string;
  PLAN097_D1_DATABASE_NAME?: string;
  PLAN097_D1_DATABASE_ID?: string;
  PLAN097_ARTIFACTS_BUCKET_NAME?: string;
  PLAN097_PREFLIGHT_SIGNING_KEY_ID?: string;
  PLAN097_PREFLIGHT_SIGNING_PRIVATE_KEY_PKCS8_BASE64?: string;
  PLAN097_PREFLIGHT_SIGNING_PUBLIC_KEY_SPKI_BASE64?: string;
};
