export const MONTH_DOCTRINE_RULE_IDS = [
  "analysis-period-identity",
  "identity-phrase",
  "pinned-identity-month",
  "public-month-selector",
  "release-month-identity",
  "retired-identity-token",
  "serialized-release-month",
] as const;

export type MonthDoctrineRuleId = (typeof MONTH_DOCTRINE_RULE_IDS)[number];

export const MONTH_DOCTRINE_DISPOSITIONS = [
  "retire-079",
  "retire-085",
  "retire-086",
  "retire-087",
  "permanent-frozen-artifact",
] as const;

export type MonthDoctrineDisposition = (typeof MONTH_DOCTRINE_DISPOSITIONS)[number];

export type MonthDoctrineAllowlistEntry = {
  file: string;
  rule: MonthDoctrineRuleId;
  count: number;
  disposition: MonthDoctrineDisposition;
  note: string;
};

// Exact occurrence counts at Plan 088 landing. Entries are sorted by file,
// then rule. Every entry is retiring initially; Plans 079 and 085-087 must
// shrink or remove their own pairs in the same commit as the production edit.
export const MONTH_DOCTRINE_ALLOWLIST = [
  {
    file: "apps/web/src/components/route/data-quality-labels.ts",
    rule: "retired-identity-token",
    count: 2,
    disposition: "retire-085",
    note: "Plan 085 renames the two legacy serving-quality literals.",
  },
  {
    file: "apps/web/src/components/route/route-fact-evidence.ts",
    rule: "retired-identity-token",
    count: 1,
    disposition: "retire-085",
    note: "Plan 085 migrates the isolated Studio detail parity read to coverage identity.",
  },
  {
    file: "apps/web/wrangler.jsonc",
    rule: "pinned-identity-month",
    count: 2,
    disposition: "retire-085",
    note: "Plan 085 deletes both serving-environment month pins.",
  },
  {
    file: "apps/web/wrangler.jsonc",
    rule: "retired-identity-token",
    count: 2,
    disposition: "retire-085",
    note: "Plan 085 deletes BASELINE_MONTH and LAST_BUILT_SPEED_MONTH.",
  },
  {
    file: "packages/analytics/src/data-products/registry.ts",
    rule: "identity-phrase",
    count: 34,
    disposition: "retire-086",
    note: "Plan 086 rewrites registry release-month identity prose.",
  },
  {
    file: "packages/analytics/src/data-products/registry.ts",
    rule: "serialized-release-month",
    count: 70,
    disposition: "retire-086",
    note: "Plan 086 renames all serialized release_month cadence literals.",
  },
  {
    file: "packages/analytics/src/evaluation/build-route-capability-manifest.ts",
    rule: "identity-phrase",
    count: 1,
    disposition: "retire-085",
    note: "Plan 085 rewrites capability freshness prose around publication coverage.",
  },
  {
    file: "packages/analytics/src/evaluation/build-route-capability-manifest.ts",
    rule: "release-month-identity",
    count: 47,
    disposition: "retire-085",
    note: "Plan 085 migrates capability builder identity to the release triple.",
  },
  {
    file: "packages/analytics/src/evaluation/build-route-capability-manifest.ts",
    rule: "retired-identity-token",
    count: 5,
    disposition: "retire-085",
    note: "Plan 085 removes capability baseline identity fields and variables.",
  },
  {
    file: "packages/analytics/src/evaluation/build-route-dossier-summary.ts",
    rule: "identity-phrase",
    count: 1,
    disposition: "retire-085",
    note: "Plan 085 rewrites dossier release-month prose.",
  },
  {
    file: "packages/analytics/src/evaluation/build-route-dossier-summary.ts",
    rule: "release-month-identity",
    count: 3,
    disposition: "retire-085",
    note: "Plan 085 migrates dossier builder identity to the release triple.",
  },
  {
    file: "packages/db/src/d1/queries/route-observed-reliability.ts",
    rule: "retired-identity-token",
    count: 2,
    disposition: "retire-085",
    note: "Plan 085 renames the non-baseline observed-month query boundary.",
  },
  {
    file: "packages/db/src/d1/queries/studio-route-index.ts",
    rule: "retired-identity-token",
    count: 2,
    disposition: "retire-085",
    note: "Plan 085 rewrites D1 serving-query comments without env month anchors.",
  },
  {
    file: "packages/domain/src/routes/index.ts",
    rule: "identity-phrase",
    count: 3,
    disposition: "retire-085",
    note: "Plan 085 rewrites public route contract descriptions around coverage.",
  },
  {
    file: "packages/domain/src/routes/index.ts",
    rule: "retired-identity-token",
    count: 8,
    disposition: "retire-085",
    note: "Plan 085 migrates public route schemas and serving-quality literals.",
  },
  {
    file: "packages/domain/src/studio/field-provenance.ts",
    rule: "identity-phrase",
    count: 2,
    disposition: "retire-085",
    note: "Plan 085 rewrites provenance notes as covered-month evidence.",
  },
  {
    file: "packages/domain/src/studio/projections.ts",
    rule: "retired-identity-token",
    count: 4,
    disposition: "retire-085",
    note: "Plan 085 migrates routes/detail outputs, then hands four payload reads to Plan 086.",
  },
  {
    file: "packages/domain/src/studio/release.ts",
    rule: "retired-identity-token",
    count: 1,
    disposition: "retire-086",
    note: "Plan 086 migrates the top-level static release payload identity.",
  },
  {
    file: "packages/domain/src/studio/route-capability.ts",
    rule: "identity-phrase",
    count: 1,
    disposition: "retire-085",
    note: "Plan 085 rewrites capability freshness documentation.",
  },
  {
    file: "packages/domain/src/studio/route-capability.ts",
    rule: "release-month-identity",
    count: 1,
    disposition: "retire-085",
    note: "Plan 085 versions the capability manifest with release identity and coverage.",
  },
  {
    file: "packages/domain/src/studio/route-dossier.ts",
    rule: "release-month-identity",
    count: 2,
    disposition: "retire-085",
    note: "Plan 085 versions both dossier release-identity members.",
  },
  {
    file: "packages/domain/src/studio/routes/index.ts",
    rule: "retired-identity-token",
    count: 3,
    disposition: "retire-085",
    note: "Plan 085 migrates Studio route responses to the release triple.",
  },
  {
    file: "packages/domain/src/studio/shared.ts",
    rule: "retired-identity-token",
    count: 2,
    disposition: "retire-085",
    note: "Plan 085 renames shared serving-quality literals.",
  },
  {
    file: "packages/domain/src/studio/snapshots.ts",
    rule: "retired-identity-token",
    count: 4,
    disposition: "retire-085",
    note: "Plan 085 migrates snapshot release anchors to release identity and coverage.",
  },
  {
    file: "packages/studio-api/src/env.ts",
    rule: "retired-identity-token",
    count: 2,
    disposition: "retire-085",
    note: "Plan 085 removes both serving month environment variables.",
  },
  {
    file: "packages/studio-api/src/public-api.ts",
    rule: "public-month-selector",
    count: 2,
    disposition: "retire-085",
    note: "Plan 085 removes the shared product selector and renames history grain to asOfMonth.",
  },
  {
    file: "packages/studio-api/src/public-api.ts",
    rule: "retired-identity-token",
    count: 17,
    disposition: "retire-085",
    note: "Plan 085 removes the exact non-map serving identity remainder.",
  },
  {
    file: "packages/studio-api/src/source-refresh.ts",
    rule: "retired-identity-token",
    count: 6,
    disposition: "retire-085",
    note: "Plan 085 replaces Worker freshness env anchors with D1-derived state.",
  },
  {
    file: "packages/studio-api/src/studio/read-handlers.ts",
    rule: "release-month-identity",
    count: 2,
    disposition: "retire-085",
    note: "Plan 085 migrates dossier reader identity fields.",
  },
  {
    file: "packages/studio-api/src/studio/read-handlers.ts",
    rule: "retired-identity-token",
    count: 58,
    disposition: "retire-085",
    note: "Plan 085 hard-cuts Studio serving responses and read models to release identity.",
  },
  {
    file: "packages/studio-api/src/studio/route-index-read-model.ts",
    rule: "identity-phrase",
    count: 2,
    disposition: "retire-085",
    note: "Plan 085 rewrites route-index caveats without baseline-month framing.",
  },
  {
    file: "packages/studio-api/src/studio/route-index-read-model.ts",
    rule: "retired-identity-token",
    count: 3,
    disposition: "retire-085",
    note: "Plan 085 migrates route-index model fields from baselineMonth.",
  },
  {
    file: "tools/pipeline-v2/src/checks/check-publish-completeness.ts",
    rule: "retired-identity-token",
    count: 2,
    disposition: "retire-085",
    note: "Plan 085 migrates the remaining Studio routes comparison pair.",
  },
  {
    file: "tools/pipeline-v2/src/commands/export/d1-inputs.ts",
    rule: "release-month-identity",
    count: 7,
    disposition: "retire-086",
    note: "Plan 086 audits frozen compatibility reads: legacy timeline 4 plus detector readiness 3.",
  },
  {
    file: "tools/pipeline-v2/src/commands/export/d1.ts",
    rule: "analysis-period-identity",
    count: 2,
    disposition: "retire-086",
    note: "Plan 086 migrates D1 export-summary identity to the release triple.",
  },
  {
    file: "tools/pipeline-v2/src/commands/export/d1.ts",
    rule: "release-month-identity",
    count: 2,
    disposition: "retire-085",
    note: "Plan 085 migrates capability and dossier builder call arguments.",
  },
  {
    file: "tools/pipeline-v2/src/commands/export/route-capability-manifest.ts",
    rule: "release-month-identity",
    count: 6,
    disposition: "retire-085",
    note: "Plan 085 removes active builder 3, then hands frozen detector 3 to Plan 086.",
  },
  {
    file: "tools/pipeline-v2/src/commands/export/route-capability-manifest.ts",
    rule: "retired-identity-token",
    count: 1,
    disposition: "retire-085",
    note: "Plan 085 renames the active capability input baseline field.",
  },
  {
    file: "tools/pipeline-v2/src/commands/export/route-dossier-summaries.ts",
    rule: "release-month-identity",
    count: 3,
    disposition: "retire-085",
    note: "Plan 085 migrates dossier summary output identity.",
  },
  {
    file: "tools/pipeline-v2/src/commands/plan/source-refresh.ts",
    rule: "identity-phrase",
    count: 1,
    disposition: "retire-087",
    note: "Plan 087 removes the final monthly-release operator prose.",
  },
  {
    file: "tools/pipeline-v2/src/commands/publish/r2-artifacts.ts",
    rule: "identity-phrase",
    count: 1,
    disposition: "retire-086",
    note: "Plan 086 rewrites remaining publish help around covered partitions.",
  },
  {
    file: "tools/pipeline-v2/src/commands/studio/build-mta-wiki-route-fixture.ts",
    rule: "retired-identity-token",
    count: 1,
    disposition: "retire-085",
    note: "Plan 085 migrates the served-response fixture shape.",
  },
  {
    file: "tools/pipeline-v2/src/commands/studio/release.ts",
    rule: "pinned-identity-month",
    count: 3,
    disposition: "retire-086",
    note: "Plan 086 deletes one hardcoded default and two pinned local D1 paths.",
  },
  {
    file: "tools/pipeline-v2/src/commands/studio/release.ts",
    rule: "retired-identity-token",
    count: 3,
    disposition: "retire-086",
    note: "Plan 086 migrates the static release payload and pinned default identity.",
  },
] as const satisfies readonly MonthDoctrineAllowlistEntry[];
