CREATE TABLE `local_gtfs_rt_alert` (
	`run_id` text NOT NULL,
	`feed_type` text NOT NULL,
	`sample_index` integer NOT NULL,
	`entity_id` text NOT NULL,
	`entity_deleted` integer NOT NULL,
	`gtfs_realtime_version` text,
	`feed_timestamp` integer,
	`cause` text,
	`effect` text,
	`active_period_json` text,
	`informed_entity_json` text,
	`url_json` text,
	`header_text_json` text,
	`description_text_json` text,
	PRIMARY KEY(`run_id`, `feed_type`, `sample_index`, `entity_id`)
);
--> statement-breakpoint
CREATE TABLE `local_gtfs_rt_parsed_snapshot` (
	`run_id` text NOT NULL,
	`feed_type` text NOT NULL,
	`sample_index` integer NOT NULL,
	`parsed_at` text NOT NULL,
	`status` text NOT NULL,
	`gtfs_realtime_version` text,
	`feed_timestamp` integer,
	`entity_count` integer NOT NULL,
	`vehicle_position_count` integer NOT NULL,
	`trip_update_count` integer NOT NULL,
	`stop_time_update_count` integer NOT NULL,
	`alert_count` integer NOT NULL,
	`error` text,
	PRIMARY KEY(`run_id`, `feed_type`, `sample_index`)
);
--> statement-breakpoint
CREATE TABLE `local_gtfs_rt_stop_time_update` (
	`run_id` text NOT NULL,
	`feed_type` text NOT NULL,
	`sample_index` integer NOT NULL,
	`entity_id` text NOT NULL,
	`update_rank` integer NOT NULL,
	`stop_sequence` integer,
	`stop_id` text,
	`arrival_delay` integer,
	`arrival_time` integer,
	`arrival_uncertainty` integer,
	`departure_delay` integer,
	`departure_time` integer,
	`departure_uncertainty` integer,
	`schedule_relationship` text,
	`assigned_stop_id` text,
	PRIMARY KEY(`run_id`, `feed_type`, `sample_index`, `entity_id`, `update_rank`)
);
--> statement-breakpoint
CREATE TABLE `local_gtfs_rt_trip_update` (
	`run_id` text NOT NULL,
	`feed_type` text NOT NULL,
	`sample_index` integer NOT NULL,
	`entity_id` text NOT NULL,
	`entity_deleted` integer NOT NULL,
	`gtfs_realtime_version` text,
	`feed_timestamp` integer,
	`source_route_id` text,
	`route_id` text,
	`trip_id` text,
	`start_date` text,
	`start_time` text,
	`direction_id` integer,
	`schedule_relationship` text,
	`vehicle_id` text,
	`vehicle_label` text,
	`vehicle_license_plate` text,
	`timestamp` integer,
	`delay` integer,
	PRIMARY KEY(`run_id`, `feed_type`, `sample_index`, `entity_id`)
);
--> statement-breakpoint
CREATE TABLE `local_gtfs_rt_vehicle_position` (
	`run_id` text NOT NULL,
	`feed_type` text NOT NULL,
	`sample_index` integer NOT NULL,
	`entity_id` text NOT NULL,
	`entity_deleted` integer NOT NULL,
	`gtfs_realtime_version` text,
	`feed_timestamp` integer,
	`source_route_id` text,
	`route_id` text,
	`trip_id` text,
	`start_date` text,
	`start_time` text,
	`direction_id` integer,
	`schedule_relationship` text,
	`vehicle_id` text,
	`vehicle_label` text,
	`vehicle_license_plate` text,
	`latitude` real,
	`longitude` real,
	`bearing` real,
	`odometer` real,
	`speed` real,
	`current_stop_sequence` integer,
	`stop_id` text,
	`current_status` text,
	`timestamp` integer,
	`congestion_level` text,
	`occupancy_status` text,
	`occupancy_percentage` real,
	PRIMARY KEY(`run_id`, `feed_type`, `sample_index`, `entity_id`)
);
