import {
  getRouteBatchStatus,
  listCorridorArtifacts,
  listCorridorHotspots,
  listCorridorInterventionContexts,
  listCorridorMonthSummaries,
  listCorridorRouteMembers,
  listCorridors,
  listInterventionEvents,
  listRouteArtifacts,
  listRouteBatchBuiltRoutes,
  listRouteBatchIssues,
  listRouteBriefPeakWindows,
  listRouteBriefSlowestWindows,
  listRouteBriefSummaries,
  listRouteBuildPlan,
  listRouteCatalog,
  listRouteComparisonRanks,
  listRouteEquityContexts,
  listRouteInterventionComparisons,
  listRouteMonthCoverage,
  listRouteMonthSourceStatuses,
  listRouteMonthTrends,
  listRouteObservedReliabilitySummaries,
  listRouteReadiness,
  listRouteReliabilityBaselines,
  listRouteReliabilityGapWindows,
  listRouteScorecards,
  type LocalPipelineDb,
} from "@bp/db/local";

export type D1CanonicalInputs = Awaited<ReturnType<typeof readLocalD1Inputs>>;
export type D1AppendixInputs = Awaited<ReturnType<typeof readLocalD1AppendixInputs>>;

export async function readLocalD1Inputs(db: LocalPipelineDb, month: string) {
  const [
    routeCatalog,
    routeCoverage,
    routeReadiness,
    routeBuildPlan,
    routeReliabilityBaseline,
    routeReliabilityGapWindows,
    routeObservedReliabilitySummaries,
    interventionEvents,
    routeInterventionComparisons,
    routeArtifacts,
    corridors,
    corridorArtifacts,
    corridorRouteMembers,
    corridorMonthSummaries,
    corridorInterventionContexts,
    corridorHotspots,
    routeMonthSourceStatuses,
    routeMonthTrends,
    routeEquityContext,
    routeScorecards,
    routeBriefSummaries,
    routeBriefPeakWindows,
    routeBriefSlowestWindows,
    routeComparisonRanks,
    routeBatchStatus,
    routeBatchBuiltRoutes,
    routeBatchIssues,
  ] = await Promise.all([
    listRouteCatalog(db),
    listRouteMonthCoverage(db, month),
    listRouteReadiness(db, month),
    listRouteBuildPlan(db, month),
    listRouteReliabilityBaselines(db, month),
    listRouteReliabilityGapWindows(db, month),
    listRouteObservedReliabilitySummaries(db, month),
    listInterventionEvents(db),
    listRouteInterventionComparisons(db, month),
    listRouteArtifacts(db, month),
    listCorridors(db),
    listCorridorArtifacts(db, month),
    listCorridorRouteMembers(db, month),
    listCorridorMonthSummaries(db, month),
    listCorridorInterventionContexts(db, month),
    listCorridorHotspots(db, month),
    listRouteMonthSourceStatuses(db, month),
    listRouteMonthTrends(db),
    listRouteEquityContexts(db, month),
    listRouteScorecards(db, month),
    listRouteBriefSummaries(db, month),
    listRouteBriefPeakWindows(db, month),
    listRouteBriefSlowestWindows(db, month),
    listRouteComparisonRanks(db, month),
    getRouteBatchStatus(db, month),
    listRouteBatchBuiltRoutes(db, month),
    listRouteBatchIssues(db, month),
  ]);

  return {
    routeCatalog,
    routeCoverage,
    routeReadiness,
    routeBuildPlan,
    routeReliabilityBaseline,
    routeReliabilityGapWindows,
    routeObservedReliabilitySummaries,
    interventionEvents,
    routeInterventionComparisons,
    routeArtifacts,
    corridors,
    corridorArtifacts,
    corridorRouteMembers,
    corridorMonthSummaries,
    corridorInterventionContexts,
    corridorHotspots,
    routeMonthSourceStatuses,
    routeMonthTrends,
    routeEquityContext,
    routeScorecards,
    routeBriefSummaries,
    routeBriefPeakWindows,
    routeBriefSlowestWindows,
    routeComparisonRanks,
    routeBatchStatus,
    routeBatchBuiltRoutes,
    routeBatchIssues,
  };
}

export async function readLocalD1AppendixInputs(db: LocalPipelineDb, month: string) {
  const [routeObservedReliabilitySummaries, routeMonthSourceStatuses] = await Promise.all([
    listRouteObservedReliabilitySummaries(db, month),
    listRouteMonthSourceStatuses(db, month),
  ]);
  return { routeObservedReliabilitySummaries, routeMonthSourceStatuses };
}
