import { privateNoStore, publicStudioCache } from "./cache-policy.js";
import { noIdempotency, requiredMutationIdempotency } from "./idempotency.js";
import type { RouteAuth, RouteSpec } from "./route-spec.js";

const publicAuth = { kind: "public" } as const satisfies RouteAuth;
const optionalSessionAuth = { kind: "optional-session" } as const satisfies RouteAuth;
const authoringAuth = {
  kind: "session",
  scopes: ["write:briefs"],
} as const satisfies RouteAuth;

function route<const TSpec extends RouteSpec>(spec: TSpec): TSpec {
  return spec;
}

export const studioApiRoutes = [
  route({
    id: "system.health",
    operationId: "getHealth",
    method: "GET",
    path: "/api/health",
    tags: ["System"],
    summary: "Return API health status.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "system.openapi",
    operationId: "getOpenApi",
    method: "GET",
    path: "/api/openapi.json",
    tags: ["System"],
    summary: "Return the Studio OpenAPI document.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "auth.me",
    operationId: "getMe",
    method: "GET",
    path: "/api/v1/me",
    tags: ["Auth"],
    summary: "Return the current Studio operator session.",
    auth: optionalSessionAuth,
    cache: privateNoStore,
    idempotency: noIdempotency,
  }),
  route({
    id: "auth.magicLink.request",
    operationId: "requestMagicLink",
    method: "POST",
    path: "/api/v1/auth/magic-link/request",
    tags: ["Auth"],
    summary: "Request a Studio magic-link sign-in email.",
    auth: publicAuth,
    cache: privateNoStore,
    idempotency: noIdempotency,
  }),
  route({
    id: "auth.magicLink.consume",
    operationId: "consumeMagicLink",
    method: "POST",
    path: "/api/v1/auth/magic-link/consume",
    tags: ["Auth"],
    summary: "Consume a Studio magic-link token.",
    auth: publicAuth,
    cache: privateNoStore,
    idempotency: noIdempotency,
  }),
  route({
    id: "auth.signout",
    operationId: "signOut",
    method: "POST",
    path: "/api/v1/auth/signout",
    tags: ["Auth"],
    summary: "Revoke the current Studio session.",
    auth: optionalSessionAuth,
    cache: privateNoStore,
    idempotency: noIdempotency,
  }),
  route({
    id: "observability.rum",
    operationId: "postRum",
    method: "POST",
    path: "/api/v1/rum",
    tags: ["Observability"],
    summary: "Record browser route performance telemetry.",
    auth: publicAuth,
    cache: privateNoStore,
    idempotency: noIdempotency,
  }),
  route({
    id: "public.status",
    operationId: "getReleaseStatus",
    method: "GET",
    path: "/api/v1/status",
    tags: ["Public"],
    summary: "Return current public serving release status.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "public.routes",
    operationId: "getRoutes",
    method: "GET",
    path: "/api/v1/routes",
    tags: ["Public"],
    summary: "List public route cards.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "public.routeProfile",
    operationId: "getRouteProfile",
    method: "GET",
    path: "/api/v1/routes/:routeId",
    tags: ["Public"],
    summary: "Return a public route profile.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "public.mapManifest",
    operationId: "getMapManifest",
    method: "GET",
    path: "/api/v1/map/manifest",
    tags: ["Public"],
    summary: "Return map artifact metadata.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "public.artifact",
    operationId: "getArtifact",
    method: "GET",
    path: "/api/v1/artifacts/:artifactKey",
    tags: ["Public"],
    summary: "Fetch a public artifact by key.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "public.hotspots",
    operationId: "getHotspots",
    method: "GET",
    path: "/api/v1/hotspots",
    tags: ["Public"],
    summary: "Return public hotspot summaries.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "public.compare",
    operationId: "getCompare",
    method: "GET",
    path: "/api/v1/compare",
    tags: ["Public"],
    summary: "Return public route comparison data.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.routes",
    operationId: "getStudioRoutes",
    method: "GET",
    path: "/api/v1/studio/routes",
    tags: ["Studio"],
    summary: "List Studio route projections.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.search",
    operationId: "searchStudio",
    method: "GET",
    path: "/api/v1/studio/search",
    tags: ["Studio"],
    summary: "Search Studio routes, findings, and briefs.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.snapshot",
    operationId: "getStudioSnapshot",
    method: "GET",
    path: "/api/v1/studio/snapshot",
    tags: ["Studio"],
    summary: "Return a compact Studio release snapshot.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.route",
    operationId: "getStudioRoute",
    method: "GET",
    path: "/api/v1/studio/routes/:routeId",
    tags: ["Studio"],
    summary: "Return a Studio route detail projection.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.routeLadder",
    operationId: "getStudioRouteLadder",
    method: "GET",
    path: "/api/v1/studio/routes/:routeId/ladder",
    tags: ["Studio"],
    summary: "Return a Studio route ladder projection.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.compare",
    operationId: "getStudioCompare",
    method: "GET",
    path: "/api/v1/studio/compare",
    tags: ["Studio"],
    summary: "Return Studio comparison projections.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.findings",
    operationId: "getStudioFindings",
    method: "GET",
    path: "/api/v1/studio/findings",
    tags: ["Studio"],
    summary: "List Studio findings.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.finding",
    operationId: "getStudioFinding",
    method: "GET",
    path: "/api/v1/studio/findings/:findingId",
    tags: ["Studio"],
    summary: "Return a Studio finding.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.briefs",
    operationId: "getStudioBriefs",
    method: "GET",
    path: "/api/v1/studio/briefs",
    tags: ["Studio"],
    summary: "List Studio briefs.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.brief",
    operationId: "getStudioBrief",
    method: "GET",
    path: "/api/v1/studio/briefs/:briefId",
    tags: ["Studio"],
    summary: "Return a Studio brief.",
    auth: optionalSessionAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.briefEvidence",
    operationId: "getStudioBriefEvidence",
    method: "GET",
    path: "/api/v1/studio/briefs/:briefId/evidence",
    tags: ["Studio"],
    summary: "Return Studio brief evidence.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.briefHistory",
    operationId: "getStudioBriefHistory",
    method: "GET",
    path: "/api/v1/studio/briefs/:briefId/history",
    tags: ["Studio"],
    summary: "Return Studio brief history.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.methods",
    operationId: "getStudioMethods",
    method: "GET",
    path: "/api/v1/studio/methods",
    tags: ["Studio"],
    summary: "Return Studio method metadata.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.docs",
    operationId: "getStudioDocs",
    method: "GET",
    path: "/api/v1/studio/docs",
    tags: ["Studio"],
    summary: "Return Studio docs projection.",
    auth: publicAuth,
    cache: publicStudioCache,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.briefs.create",
    operationId: "createStudioBrief",
    method: "POST",
    path: "/api/v1/studio/briefs",
    tags: ["Studio Authoring"],
    summary: "Create a Studio brief draft.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraft",
    operationId: "patchStudioBriefDraft",
    method: "PATCH",
    path: "/api/v1/studio/briefs/:briefId/draft",
    tags: ["Studio Authoring"],
    summary: "Patch a Studio brief draft.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraft.generate",
    operationId: "generateStudioBriefDraft",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/generate",
    tags: ["Studio Authoring"],
    summary: "Queue a Studio brief draft AI-generation run.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefAgentRuns.create",
    operationId: "createStudioBriefAgentRun",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/agent-runs",
    tags: ["Studio Authoring"],
    summary: "Start a Studio brief authoring agent run.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefAgentRun",
    operationId: "getStudioBriefAgentRun",
    method: "GET",
    path: "/api/v1/studio/briefs/:briefId/draft/agent-runs/:runId",
    tags: ["Studio Authoring"],
    summary: "Fetch one Studio brief authoring agent run.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.briefAgentRun.proposeEdit",
    operationId: "proposeStudioBriefAgentEdit",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/agent-runs/:runId/propose-edit",
    tags: ["Studio Authoring"],
    summary: "Submit structured agent edit operations.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefAgentProposal",
    operationId: "getStudioBriefAgentProposal",
    method: "GET",
    path: "/api/v1/studio/briefs/:briefId/draft/proposals/:proposalId",
    tags: ["Studio Authoring"],
    summary: "Fetch one stored Studio brief agent proposal.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.briefAgentProposal.apply",
    operationId: "applyStudioBriefAgentProposal",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/proposals/:proposalId/apply",
    tags: ["Studio Authoring"],
    summary: "Apply a Studio brief agent proposal.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefAgentProposal.reject",
    operationId: "rejectStudioBriefAgentProposal",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/proposals/:proposalId/reject",
    tags: ["Studio Authoring"],
    summary: "Reject a Studio brief agent proposal.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraftVersions",
    operationId: "listStudioBriefDraftVersions",
    method: "GET",
    path: "/api/v1/studio/briefs/:briefId/draft/versions",
    tags: ["Studio Authoring"],
    summary: "List Studio brief draft version milestones.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.briefDraftVersion.restore",
    operationId: "restoreStudioBriefDraftVersion",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/versions/:versionId/restore",
    tags: ["Studio Authoring"],
    summary: "Restore a Studio brief draft version.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraftClaims.create",
    operationId: "addStudioBriefDraftClaim",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/claims",
    tags: ["Studio Authoring"],
    summary: "Add a claim to a Studio brief draft.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraftClaim.patch",
    operationId: "updateStudioBriefDraftClaim",
    method: "PATCH",
    path: "/api/v1/studio/briefs/:briefId/draft/claims/:claimN",
    tags: ["Studio Authoring"],
    summary: "Update one Studio brief draft claim.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraftClaim.delete",
    operationId: "deleteStudioBriefDraftClaim",
    method: "DELETE",
    path: "/api/v1/studio/briefs/:briefId/draft/claims/:claimN",
    tags: ["Studio Authoring"],
    summary: "Delete one Studio brief draft claim.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraftBlocks.create",
    operationId: "addStudioBriefDraftBlock",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/blocks",
    tags: ["Studio Authoring"],
    summary: "Add a block to a Studio brief draft.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraftBlock.patch",
    operationId: "updateStudioBriefDraftBlock",
    method: "PATCH",
    path: "/api/v1/studio/briefs/:briefId/draft/blocks/:blockId",
    tags: ["Studio Authoring"],
    summary: "Update one Studio brief draft block.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraftBlock.delete",
    operationId: "deleteStudioBriefDraftBlock",
    method: "DELETE",
    path: "/api/v1/studio/briefs/:briefId/draft/blocks/:blockId",
    tags: ["Studio Authoring"],
    summary: "Delete one Studio brief draft block.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraftRefs.resolve",
    operationId: "resolveStudioBriefDraftRefs",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/refs/resolve",
    tags: ["Studio Authoring"],
    summary: "Resolve refs for a Studio brief draft.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraftRefs",
    operationId: "fetchStudioBriefDraftRefs",
    method: "GET",
    path: "/api/v1/studio/briefs/:briefId/draft/refs",
    tags: ["Studio Authoring"],
    summary: "List refs for a Studio brief draft.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.briefDraftRefs.replace",
    operationId: "replaceStudioBriefDraftRefs",
    method: "PUT",
    path: "/api/v1/studio/briefs/:briefId/draft/refs",
    tags: ["Studio Authoring"],
    summary: "Replace refs for a Studio brief draft.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraft.attach",
    operationId: "attachStudioBriefDraftBlock",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/attach",
    tags: ["Studio Authoring"],
    summary: "Attach a captured object to a Studio brief draft.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraftComments",
    operationId: "listStudioBriefDraftComments",
    method: "GET",
    path: "/api/v1/studio/briefs/:briefId/draft/comments",
    tags: ["Studio Authoring"],
    summary: "List draft-private review threads.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.briefDraftComments.create",
    operationId: "createStudioBriefDraftComment",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/comments",
    tags: ["Studio Authoring"],
    summary: "Create a draft-private review thread.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraftComment.patch",
    operationId: "updateStudioBriefDraftComment",
    method: "PATCH",
    path: "/api/v1/studio/briefs/:briefId/draft/comments/:commentId",
    tags: ["Studio Authoring"],
    summary: "Update a draft-private review thread.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraftComment.reply",
    operationId: "replyStudioBriefDraftComment",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/comments/:commentId/replies",
    tags: ["Studio Authoring"],
    summary: "Reply to a draft-private review thread.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraftComment.acceptSuggestion",
    operationId: "acceptStudioBriefDraftSuggestion",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/comments/:commentId/accept-suggestion",
    tags: ["Studio Authoring"],
    summary: "Accept a draft-private suggested edit.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraft.validate",
    operationId: "validateStudioBriefDraft",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/validate",
    tags: ["Studio Authoring"],
    summary: "Refresh deterministic validation checks for a Studio brief draft.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraft.review",
    operationId: "requestStudioBriefDraftReview",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/review",
    tags: ["Studio Authoring"],
    summary: "Request review for a Studio brief draft.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraft.verdict",
    operationId: "submitStudioBriefDraftVerdict",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/verdict",
    tags: ["Studio Authoring"],
    summary: "Submit a review verdict for a Studio brief draft.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraft.publish",
    operationId: "publishStudioBriefDraftCandidate",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/publish",
    tags: ["Studio Authoring"],
    summary: "Mark a Studio brief draft as a publish candidate.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraft.retract",
    operationId: "retractStudioBriefDraftCandidate",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/retract",
    tags: ["Studio Authoring"],
    summary: "Retract a Studio brief draft publish candidate.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraft.promotionReceipt",
    operationId: "recordStudioBriefPromotionReceipt",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft/promotion-receipt",
    tags: ["Studio Authoring"],
    summary: "Record an offline promotion receipt.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
  route({
    id: "studio.briefDraft.publishCandidateExport",
    operationId: "fetchStudioBriefPublishCandidateExport",
    method: "GET",
    path: "/api/v1/studio/briefs/:briefId/draft/publish-candidate-export",
    tags: ["Studio Authoring"],
    summary: "Fetch a publish-candidate export payload.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: noIdempotency,
  }),
  route({
    id: "studio.briefDraftWildcard",
    operationId: "handleStudioBriefDraftSubresource",
    method: "POST",
    path: "/api/v1/studio/briefs/:briefId/draft*",
    tags: ["Studio Authoring"],
    summary: "Handle a Studio brief draft subresource.",
    auth: authoringAuth,
    cache: privateNoStore,
    idempotency: requiredMutationIdempotency,
  }),
] as const satisfies readonly RouteSpec[];

export type StudioApiRoute = (typeof studioApiRoutes)[number];
export type StudioApiRouteId = StudioApiRoute["id"];

export function getStudioApiRoute(routeId: StudioApiRouteId): StudioApiRoute {
  const route = studioApiRoutes.find((candidate) => candidate.id === routeId);
  if (route === undefined) {
    throw new Error(`Unknown Studio API route: ${routeId}`);
  }

  return route;
}
