CREATE TABLE `route_observed_reliability_summary` (
	`route_id` text NOT NULL,
	`month` text NOT NULL,
	`run_id` text NOT NULL,
	`reliability_status` text NOT NULL,
	`min_sample_threshold` integer NOT NULL,
	`sample_count` integer NOT NULL,
	`stop_count` integer NOT NULL,
	`direction_count` integer NOT NULL,
	`average_observed_headway_minutes` real,
	`median_observed_headway_minutes` real,
	`p90_observed_headway_minutes` real,
	`max_observed_headway_minutes` real,
	`scheduled_median_headway_minutes` real,
	`bunching_threshold_minutes` real,
	`long_gap_threshold_minutes` real,
	`observed_bunching_share` real,
	`observed_long_gap_share` real,
	`expected_wait_minutes` real,
	`scheduled_expected_wait_minutes` real,
	`excess_wait_minutes` real,
	`wait_reliability_ratio` real,
	PRIMARY KEY(`route_id`, `month`, `run_id`)
);
