import { Effect } from "effect";
import { runPipelineFileSystemBoundary } from "../../effect/file-system.ts";
import { fromRepoRoot } from "../../lib/paths.ts";

// The public origin used for canonical/sitemap URLs. Matches apps/web SEO serving.
export const SITEMAP_ORIGIN = "https://buspriorityimpact.studio";

// Generated artifact locations (committed, consumed by the @bp/web worker build).
const SEO_MANIFEST_PATH = "apps/web/src/studio/seo-manifest.gen.ts";
const SITEMAP_PATH = "apps/web/public/sitemap.xml";

// Static public pages that always exist regardless of the release contents.
const STATIC_PUBLIC_PATHS = ["/", "/map", "/interventions", "/methods"] as const;

export type SeoTitleManifest = {
  generatedAt: string;
  routes: Array<[string, string]>;
};

type ReleaseForSeo = {
  generatedAt: string;
  routes: ReadonlyArray<{ slug: string; label: string; sbs: boolean }>;
};

/**
 * Derive the SEO title manifest from the release payload. This is the route
 * title source the worker uses when injecting page `<head>`s.
 */
export function buildSeoTitleManifest(release: ReleaseForSeo): SeoTitleManifest {
  return {
    generatedAt: release.generatedAt,
    routes: release.routes.map((route) => [
      route.slug,
      route.sbs ? `${route.label} SBS` : route.label,
    ]),
  };
}

export function renderSeoManifestModule(manifest: SeoTitleManifest): string {
  return `// AUTO-GENERATED by \`studio release\` (tools/pipeline-v2/src/commands/studio/_release-seo.ts).
// Do not edit by hand. Regenerate with: bun --filter @bp/web build:studio-release
export const SEO_MANIFEST_GENERATED_AT = ${JSON.stringify(manifest.generatedAt)};

export const routeTitles: ReadonlyMap<string, string> = new Map([
${renderEntries(manifest.routes)}
]);
`;
}

export function buildSitemapXml(origin: string, manifest: SeoTitleManifest): string {
  const paths = [...STATIC_PUBLIC_PATHS] as string[];
  for (const [slug] of manifest.routes) {
    paths.push(`/routes/${slug}`);
  }

  const urls = paths
    .map((path) => `  <url><loc>${escapeXml(new URL(path, origin).toString())}</loc></url>`)
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

/**
 * Emit the committed SEO manifest module and sitemap from the release payload.
 * Called from the studio release pipeline after projections are written.
 */
export async function writeSeoArtifacts(release: ReleaseForSeo): Promise<void> {
  const manifest = buildSeoTitleManifest(release);
  await runPipelineFileSystemBoundary({
    command: "studio.release",
    operation: "writeSeoArtifacts",
    run: (files) =>
      Effect.gen(function* () {
        yield* files.writeText({
          command: "studio.release",
          operation: "writeSeoManifest",
          path: fromRepoRoot(SEO_MANIFEST_PATH),
          contents: renderSeoManifestModule(manifest),
        });
        yield* files.writeText({
          command: "studio.release",
          operation: "writeSitemap",
          path: fromRepoRoot(SITEMAP_PATH),
          contents: buildSitemapXml(SITEMAP_ORIGIN, manifest),
        });
      }),
  });
}

function renderEntries(pairs: Array<[string, string]>): string {
  return pairs
    .map(([key, value]) => `  [${JSON.stringify(key)}, ${JSON.stringify(value)}],`)
    .join("\n");
}

function escapeXml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
}
