import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { fromRepoRoot } from "../../lib/paths.ts";

// The public origin used for canonical/sitemap URLs. Matches apps/web SEO serving.
export const SITEMAP_ORIGIN = "https://buspriorityimpact.studio";

// Generated artifact locations (committed, consumed by the @bp/web worker build).
const SEO_MANIFEST_PATH = "apps/web/src/studio/seo-manifest.gen.ts";
const SITEMAP_PATH = "apps/web/public/sitemap.xml";

// Static public pages that always exist regardless of the release contents.
// `/search` is intentionally excluded: it is a parameterized results page, not a
// canonical content URL, so it does not belong in the sitemap.
const STATIC_PUBLIC_PATHS = ["/", "/compare", "/findings", "/briefs", "/methods", "/docs"] as const;

export type SeoTitleManifest = {
  generatedAt: string;
  routes: Array<[string, string]>;
  findings: Array<[string, string]>;
  briefs: Array<[string, string]>;
};

type ReleaseForSeo = {
  generatedAt: string;
  routes: ReadonlyArray<{ slug: string; label: string; sbs: boolean }>;
  findings: ReadonlyArray<{ id: string; title: string }>;
  briefs: ReadonlyArray<{ id: string; title: string }>;
};

/**
 * Derive the SEO title manifest from the release payload. This is the single
 * source of truth for the route/finding/brief titles the worker injects into
 * page `<head>`s, so the titles can never drift from what is actually served.
 */
export function buildSeoTitleManifest(release: ReleaseForSeo): SeoTitleManifest {
  return {
    generatedAt: release.generatedAt,
    routes: release.routes.map((route) => [
      route.slug,
      route.sbs ? `${route.label} SBS` : route.label,
    ]),
    findings: release.findings.map((finding) => [finding.id, finding.title]),
    briefs: release.briefs.map((brief) => [brief.id, brief.title]),
  };
}

export function renderSeoManifestModule(manifest: SeoTitleManifest): string {
  return `// AUTO-GENERATED by \`studio release\` (tools/pipeline-v2/src/commands/studio/_release-seo.ts).
// Do not edit by hand. Regenerate with: bun --filter @bp/web build:studio-release
export const SEO_MANIFEST_GENERATED_AT = ${JSON.stringify(manifest.generatedAt)};

export const routeTitles: ReadonlyMap<string, string> = new Map([
${renderEntries(manifest.routes)}
]);

export const findingTitles: ReadonlyMap<string, string> = new Map([
${renderEntries(manifest.findings)}
]);

export const briefTitles: ReadonlyMap<string, string> = new Map([
${renderEntries(manifest.briefs)}
]);
`;
}

export function buildSitemapXml(origin: string, manifest: SeoTitleManifest): string {
  const paths = [...STATIC_PUBLIC_PATHS] as string[];
  for (const [slug] of manifest.routes) {
    paths.push(`/routes/${slug}`, `/routes/${slug}/ladder`);
  }
  for (const [id] of manifest.findings) {
    paths.push(`/findings/${id}`);
  }
  for (const [id] of manifest.briefs) {
    paths.push(`/briefs/${id}`, `/briefs/${id}/evidence`);
  }

  const urls = paths
    .map((path) => `  <url><loc>${escapeXml(new URL(path, origin).toString())}</loc></url>`)
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

/**
 * Emit the committed SEO manifest module and sitemap from the release payload.
 * Called from the studio release pipeline after projections are written.
 */
export async function writeSeoArtifacts(release: ReleaseForSeo): Promise<void> {
  const manifest = buildSeoTitleManifest(release);
  await writeFileEnsuringDir(fromRepoRoot(SEO_MANIFEST_PATH), renderSeoManifestModule(manifest));
  await writeFileEnsuringDir(fromRepoRoot(SITEMAP_PATH), buildSitemapXml(SITEMAP_ORIGIN, manifest));
}

function renderEntries(pairs: Array<[string, string]>): string {
  return pairs
    .map(([key, value]) => `  [${JSON.stringify(key)}, ${JSON.stringify(value)}],`)
    .join("\n");
}

function escapeXml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
}

async function writeFileEnsuringDir(path: string, contents: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, contents);
}
