import {
  getRouteBatchStatus,
  listInterventionEvents,
  listRouteBatchBuiltRoutes,
  listRouteBatchIssues,
  listRouteBriefPeakWindows,
  listRouteBriefSlowestWindows,
  listRouteBriefSummaries,
  listRouteBuildPlan,
  listRouteCatalog,
  listRouteComparisonRanks,
  listRouteEquityContexts,
  listRouteInterventionComparisons,
  listRouteMonthCoverage,
  listRouteMonthSourceStatuses,
  listRouteMonthTrends,
  listRouteObservedReliabilitySummaries,
  listRouteReadiness,
  listRouteReliabilityBaselines,
  listRouteReliabilityGapWindows,
  listRouteScorecards,
} from "@bp/db/local";
import { withLocalPipelineDb } from "../../lib/local-db.js";

export async function readLocalD1Inputs(path: string, month: string) {
  return withLocalPipelineDb(path, async (local) => {
    const [
      routeCatalog,
      routeCoverage,
      routeReadiness,
      routeBuildPlan,
      routeReliabilityBaseline,
      routeReliabilityGapWindows,
      routeObservedReliabilitySummaries,
      interventionEvents,
      routeInterventionComparisons,
      routeMonthSourceStatuses,
      routeMonthTrends,
      routeEquityContext,
      routeScorecards,
      routeBriefSummaries,
      routeBriefPeakWindows,
      routeBriefSlowestWindows,
      routeComparisonRanks,
      routeBatchStatus,
      routeBatchBuiltRoutes,
      routeBatchIssues,
    ] = await Promise.all([
      listRouteCatalog(local.db),
      listRouteMonthCoverage(local.db, month),
      listRouteReadiness(local.db, month),
      listRouteBuildPlan(local.db, month),
      listRouteReliabilityBaselines(local.db, month),
      listRouteReliabilityGapWindows(local.db, month),
      listRouteObservedReliabilitySummaries(local.db, month),
      listInterventionEvents(local.db),
      listRouteInterventionComparisons(local.db, month),
      listRouteMonthSourceStatuses(local.db, month),
      listRouteMonthTrends(local.db),
      listRouteEquityContexts(local.db, month),
      listRouteScorecards(local.db, month),
      listRouteBriefSummaries(local.db, month),
      listRouteBriefPeakWindows(local.db, month),
      listRouteBriefSlowestWindows(local.db, month),
      listRouteComparisonRanks(local.db, month),
      getRouteBatchStatus(local.db, month),
      listRouteBatchBuiltRoutes(local.db, month),
      listRouteBatchIssues(local.db, month),
    ]);

    return {
      routeCatalog,
      routeCoverage,
      routeReadiness,
      routeBuildPlan,
      routeReliabilityBaseline,
      routeReliabilityGapWindows,
      routeObservedReliabilitySummaries,
      interventionEvents,
      routeInterventionComparisons,
      routeMonthSourceStatuses,
      routeMonthTrends,
      routeEquityContext,
      routeScorecards,
      routeBriefSummaries,
      routeBriefPeakWindows,
      routeBriefSlowestWindows,
      routeComparisonRanks,
      routeBatchStatus,
      routeBatchBuiltRoutes,
      routeBatchIssues,
    };
  });
}
